"""Keeping LiteLLM's model list in sync with what is actually on this machine.

The design turns on one trick. ruti loads every local model under an identifier that
is also its LiteLLM `model_name`, and LiteLLM passes that name through to LM Studio
untouched. Swapping which model is *resident* therefore requires no proxy change at
all -- no restart, no config write. The proxy only needs updating when the set of
models on disk changes, which is rare and always user-initiated.

The entries live in a separate `models.generated.yaml` pulled in by `include:`, so the
hand-written `config.yaml` and its comments are never rewritten by a program. One
constraint follows from how LiteLLM merges includes: list-valued keys are extended but
dict-valued keys are *replaced*, so the generated file must contain `model_list` and
nothing else or it would silently clobber `litellm_settings`.

Health checks always use `/health/liveliness`. The bare `/health` endpoint dials every
configured backend, so a stopped LM Studio makes it hang rather than answer.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import httpx
import yaml

from .config import (
    LITELLM_CONFIG, LITELLM_GENERATED, LITELLM_PROVIDERS, LMSTUDIO_BASE, PROXY_BASE,
)

GENERATED_HEADER = """\
# Generated by `ruti models sync` -- do not edit by hand; changes are overwritten.
#
# One entry per model on disk. `model_name` matches the identifier ruti passes to
# `lms load --identifier`, which is what lets a model swap happen without touching
# the proxy. Only `model_list` belongs here: LiteLLM replaces dict-valued keys when
# merging an include, so a stray `litellm_settings` block would silently clobber the
# one in config.yaml.
"""

PROVIDERS_HEADER = """\
# Generated by `ruti provider add` -- do not edit by hand; changes are overwritten.
#
# Remote providers. Keys are never written here: each entry refers to an environment
# variable that start-litellm.ps1 loads from the gitignored .env at startup.
"""

INCLUDES = (LITELLM_GENERATED, LITELLM_PROVIDERS)


def read_config() -> dict[str, Any]:
    try:
        return yaml.safe_load(LITELLM_CONFIG.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        return {}


def missing_includes() -> list[Path]:
    """Generated files that config.yaml does not pull in."""
    declared = {Path(str(i)).name for i in (read_config().get("include") or [])}
    return [path for path in INCLUDES if path.name not in declared]


def include_is_wired() -> bool:
    return not missing_includes()


def wire_include() -> bool:
    """Ensure config.yaml includes every generated file. True if it changed anything.

    Done as a targeted text insertion rather than a YAML round-trip so the file's
    explanatory comments survive.
    """
    missing = missing_includes()
    if not missing:
        return False

    # LiteLLM refuses to start when an included path does not exist, so create any
    # stub before naming it.
    for path in missing:
        if not path.exists():
            _write_yaml(path, [], GENERATED_HEADER if path is LITELLM_GENERATED else PROVIDERS_HEADER)

    text = LITELLM_CONFIG.read_text(encoding="utf-8")
    if "include:" in text:
        lines = text.splitlines()
        at = next(i for i, line in enumerate(lines) if line.startswith("include:"))
        for path in missing:
            lines.insert(at + 1, f"  - {path.name}")
        LITELLM_CONFIG.write_text("\n".join(lines) + "\n", encoding="utf-8")
    else:
        block = (
            "# Generated model lists, rebuilt by `ruti models sync` and `ruti provider add`.\n"
            "# Editing them by hand is pointless -- they are overwritten.\n"
            "include:\n"
            + "".join(f"  - {path.name}\n" for path in missing)
            + "\n"
        )
        LITELLM_CONFIG.write_text(block + text, encoding="utf-8")
    return True


def _write_yaml(path: Path, entries: list[dict[str, Any]], header: str) -> None:
    body = yaml.safe_dump(
        {"model_list": entries}, sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    path.write_text(header + "\n" + body, encoding="utf-8")


def write_generated(entries: list[dict[str, Any]]) -> None:
    """Rewrite models.generated.yaml (local models) from scratch."""
    _write_yaml(LITELLM_GENERATED, entries, GENERATED_HEADER)


def write_providers(entries: list[dict[str, Any]]) -> None:
    """Rewrite providers.generated.yaml (remote providers) from scratch."""
    _write_yaml(LITELLM_PROVIDERS, entries, PROVIDERS_HEADER)


def local_entry(identifier: str) -> dict[str, Any]:
    """A LiteLLM entry for a model served by LM Studio under `identifier`."""
    return {
        "model_name": identifier,
        "litellm_params": {
            "model": f"openai/{identifier}",
            "api_base": f"{LMSTUDIO_BASE}/v1",
            "api_key": "none",
        },
    }


def liveliness(timeout: float = 5.0) -> bool:
    """Is the proxy up? Never call bare /health -- it dials backends and can hang."""
    try:
        return httpx.get(f"{PROXY_BASE}/health/liveliness", timeout=timeout).status_code == 200
    except httpx.HTTPError:
        return False


def served_models(timeout: float = 5.0) -> list[str]:
    """Model names the proxy is currently serving."""
    try:
        response = httpx.get(f"{PROXY_BASE}/v1/models", timeout=timeout)
        response.raise_for_status()
        return [entry["id"] for entry in response.json().get("data", [])]
    except (httpx.HTTPError, KeyError, ValueError):
        return []


def warm_up(model_name: str, timeout: float = 60.0) -> bool:
    """Send a one-token request to clear any router cooldown after a reload.

    LiteLLM cools a deployment down for `cooldown_time` seconds after `allowed_fails`
    failures. Unloading a model mid-flight trips that, so a freshly reloaded model can
    be unreachable for a minute unless something pokes it.
    """
    try:
        response = httpx.post(
            f"{PROXY_BASE}/v1/chat/completions",
            json={
                "model": model_name,
                "messages": [{"role": "user", "content": "ok"}],
                "max_tokens": 1,
            },
            timeout=timeout,
        )
        return response.status_code == 200
    except httpx.HTTPError:
        return False
